"""Vendor-specific format adapters for materializing OCD configuration.

Transforms content from the bundled SQLite database into each vendor's
expected directory layout and file format. The canonical source is
always content.db; vendor adapters translate formats.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

# ── Aider ──────────────────────────────────────────────────────────────────


def materialize_aider(db: sqlite3.Connection, target: Path, force: bool = False) -> dict[str, int]:
    """Materialize OCD configuration for Aider.

    Creates CONVENTIONS.md (project rules + agent descriptions) and
    .aider.conf.yml (with read: entries pointing to CONVENTIONS.md).
    """
    counts: dict[str, int] = {}
    target.mkdir(parents=True, exist_ok=True)

    # CONVENTIONS.md — all rules + agent summaries
    lines = ["# Project Conventions (auto-generated by ocd-materialize)", ""]
    rows = db.execute("SELECT name, description, body FROM rules ORDER BY name").fetchall()
    for name, description, body in rows:
        lines.append(f"## {name}")
        lines.append(f"_{description}_")
        lines.append("")
        lines.append(body.strip())
        lines.append("")
    agent_rows = db.execute("SELECT name, frontmatter, body FROM agents ORDER BY name").fetchall()
    if agent_rows:
        lines.append("## Agents")
        lines.append("")
        for name, _frontmatter, body in agent_rows:
            first_line = body.strip().split("\n")[0] if body.strip() else ""
            lines.append(f"- **{name}**: {first_line}")
        lines.append("")

    conventions_path = target / "CONVENTIONS.md"
    if not conventions_path.exists() or force:
        conventions_path.write_text("\n".join(lines) + "\n")
        counts["conventions"] = 1
    else:
        counts["conventions"] = 0

    # .aider.conf.yml
    conf_lines = [
        "# Auto-generated by ocd-materialize — do not edit manually",
        "read:",
        "  - CONVENTIONS.md",
    ]
    conf_path = target / ".aider.conf.yml"
    if not conf_path.exists() or force:
        conf_path.write_text("\n".join(conf_lines) + "\n")
        counts["config"] = 1
    else:
        counts["config"] = 0

    return counts


# ── Cursor ─────────────────────────────────────────────────────────────────


def materialize_cursor(db: sqlite3.Connection, target: Path, force: bool = False) -> dict[str, int]:
    """Materialize OCD configuration for Cursor.

    Creates .cursor/rules/*.mdc files with YAML frontmatter containing
    description, globs, and alwaysApply fields.
    """
    target.mkdir(parents=True, exist_ok=True)
    count = 0
    rows = db.execute("SELECT name, description, paths, body FROM rules ORDER BY name").fetchall()
    for name, description, paths, body in rows:
        path = target / f"{name}.mdc"
        if path.exists() and not force:
            continue
        frontmatter_lines = ["---"]
        frontmatter_lines.append(f"description: {_yaml_quote(description)}")
        if paths:
            frontmatter_lines.append(f"globs: {paths}")
        else:
            frontmatter_lines.append("alwaysApply: true")
        frontmatter_lines.append("---")
        content = "\n".join(frontmatter_lines) + "\n\n" + body.strip() + "\n"
        path.write_text(content)
        count += 1
    return {"rules": count}


# ── GitHub Copilot ──────────────────────────────────────────────────────────


def materialize_copilot(
    db: sqlite3.Connection, target: Path, force: bool = False
) -> dict[str, int]:
    """Materialize OCD configuration for GitHub Copilot.

    Creates .github/copilot-instructions.md (repo-wide instructions)
    and .github/instructions/*.instructions.md (path-scoped rules).
    """
    github_dir = target / ".github"
    github_dir.mkdir(parents=True, exist_ok=True)
    instructions_dir = github_dir / "instructions"
    instructions_dir.mkdir(parents=True, exist_ok=True)
    counts: dict[str, int] = {"global": 0, "scoped": 0}

    # Global copilot-instructions.md — all rules concatenated
    rows = db.execute("SELECT name, description, body FROM rules ORDER BY name").fetchall()
    global_lines = ["# Project Instructions (auto-generated by ocd-materialize)", ""]
    for name, description, body in rows:
        global_lines.append(f"## {name}")
        global_lines.append(f"_{description}_")
        global_lines.append("")
        global_lines.append(body.strip())
        global_lines.append("")

    global_path = github_dir / "copilot-instructions.md"
    if not global_path.exists() or force:
        global_path.write_text("\n".join(global_lines) + "\n")
        counts["global"] = 1

    # Path-scoped instructions — one .instructions.md per rule with paths
    scoped_rows = db.execute(
        "SELECT name, description, paths, body "
        "FROM rules WHERE paths IS NOT NULL AND paths != '' ORDER BY name"
    ).fetchall()
    for name, _description, _paths, body in scoped_rows:
        inst_path = instructions_dir / f"{name}.instructions.md"
        if inst_path.exists() and not force:
            continue
        frontmatter = [
            "---",
            f"applyTo: '{_paths}'" if _paths else "applyTo: '**'",
            "---",
            "",
        ]
        content = "\n".join(frontmatter) + body.strip() + "\n"
        inst_path.write_text(content)
        counts["scoped"] += 1

    return counts


# ── Windsurf ───────────────────────────────────────────────────────────────


def materialize_windsurf(
    db: sqlite3.Connection, target: Path, force: bool = False
) -> dict[str, int]:
    """Materialize OCD configuration for Windsurf (Codeium).

    Creates .windsurf/rules/*.md files with YAML frontmatter
    containing trigger, description, and globs fields.
    """
    target.mkdir(parents=True, exist_ok=True)
    count = 0
    rows = db.execute("SELECT name, description, paths, body FROM rules ORDER BY name").fetchall()
    for name, description, paths, body in rows:
        path = target / f"{name}.md"
        if path.exists() and not force:
            continue
        frontmatter_lines = ["---"]
        frontmatter_lines.append("trigger: always")
        frontmatter_lines.append(f"description: {_yaml_quote(description)}")
        if paths:
            frontmatter_lines.append(f"globs: {paths}")
        frontmatter_lines.append("---")
        content = "\n".join(frontmatter_lines) + "\n\n" + body.strip() + "\n"
        path.write_text(content)
        count += 1
    return {"rules": count}


# ── Amazon Q ────────────────────────────────────────────────────────────────


def materialize_amazonq(
    db: sqlite3.Connection, target: Path, force: bool = False
) -> dict[str, int]:
    """Materialize OCD configuration for Amazon Q Developer.

    Creates .amazonq/rules/*.md files with Purpose, Instructions,
    and Priority sections.
    """
    target.mkdir(parents=True, exist_ok=True)
    count = 0
    rows = db.execute("SELECT name, description, body FROM rules ORDER BY name").fetchall()
    for name, description, body in rows:
        path = target / f"{name}.md"
        if path.exists() and not force:
            continue
        lines = [
            f"# {name.replace('-', ' ').title()}",
            "",
            f"**Purpose:** {description}",
            "",
            "**Instructions:**",
            "",
        ]
        for line in body.strip().splitlines():
            lines.append(f"{line}")
        lines.append("")
        lines.append("**Priority:** high")
        lines.append("")
        path.write_text("\n".join(lines))
        count += 1
    return {"rules": count}


# ── AGENTS.md (cross-vendor) ────────────────────────────────────────────────


def generate_agents_md(db: sqlite3.Connection) -> str:
    """Generate a project-root AGENTS.md file.

    Produces a condensed, vendor-neutral instruction file that any
    LLM tool can read. Not a copy of .claude/ content — a synthesis.
    """
    lines = ["# O.C.D. Project Agents", ""]

    # Standards reference (version + hash only, not full text)
    row = db.execute("SELECT version, hash FROM standards WHERE id = 1").fetchone()
    if row:
        version, hash_val = row
        lines.append(f"Standards reference: v{version} [{hash_val}]")
        lines.append("")

    # Agent manifest
    lines.append("## Agents")
    lines.append("")
    agents = db.execute("SELECT name, frontmatter, body FROM agents ORDER BY name").fetchall()
    for name, _frontmatter, body in agents:
        first_line = body.strip().split("\n")[0] if body.strip() else ""
        lines.append(f"- **{name}**: {first_line}")
    lines.append("")

    # Key rules (condensed)
    lines.append("## Key Rules")
    lines.append("")
    rules = db.execute("SELECT name, description FROM rules ORDER BY name").fetchall()
    for name, description in rules:
        lines.append(f"- **{name}**: {description}")
    lines.append("")

    # Skills summary
    lines.append("## Skills")
    lines.append("")
    skills = db.execute("SELECT name, description FROM skills ORDER BY name").fetchall()
    for name, description in skills:
        lines.append(f"- **{name}**: {description}")
    lines.append("")

    return "\n".join(lines) + "\n"


# ── Helpers ──────────────────────────────────────────────────────────────────

VENDORS = {
    "aider": materialize_aider,
    "cursor": materialize_cursor,
    "copilot": materialize_copilot,
    "windsurf": materialize_windsurf,
    "amazonq": materialize_amazonq,
}


VENDOR_TARGETS = {
    "aider": ".aider",
    "cursor": ".cursor/rules",
    "copilot": ".",
    "windsurf": ".windsurf/rules",
    "amazonq": ".amazonq/rules",
}


def _yaml_quote(value: str) -> str:
    """Quote a YAML value if it contains special characters."""
    if any(
        c in value
        for c in (
            ":",
            "#",
            "{",
            "}",
            "[",
            "]",
            ",",
            "&",
            "*",
            "?",
            "|",
            "-",
            "<",
            ">",
            "=",
            "!",
            "%",
            "@",
            "`",
        )
    ):
        return f'"{value}"'
    return value
